config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  get '/users', to: 'users#index'
  get '/profile', to: 'users#edit'
  post '/profile', to: 'users#update'
  get '/users/:id/manage', to: 'users#manage', as: 'user_managing'
  post '/users/:id/apply_managing', to: 'users#apply_managing'
  delete '/users/:id/delete', to: 'users#destroy', as: 'delete_user'

  get '/black_list', to: 'blocked_users#index', as: 'black_list'
  get '/black_list/new', to: 'blocked_users#new', as: 'new_blocked_user'
  post '/black_list/add_user', to: 'blocked_users#add_user'
  delete '/blocked_user/:id/delete', to: 'blocked_users#destroy', as: 'delete_blocked_user'

  get 'chats/search', to: 'chats#search' # app interpreters 'search' as id. That is why it is on the first place
  resources :chats
  get '/chats/:id/users_list', to: 'chats#users_list', as: 'chat_users_list'
  post '/chats/:id/add_user', to: 'chats#add_user'
  post '/chats/:id/delete_user', to: 'chats#delete_user'
  get '/chats/:id/manage', to: 'chats#manage', as: 'chat_manging'
  post '/chats/:id/apply_managing', to: 'chats#apply_managing'
  post '/chats/:id/add_message', to: 'chats#add_message'

  get 'system_settings/edit', to: 'system_settings#edit', as: 'system_settings'
  post 'system_settings/update', to: 'system_settings#update'

  root to: "chats#index"
end

app/models/user.rb
class User < ApplicationRecord
  include Elasticsearch::Model
  include Elasticsearch::Model::Callbacks

  ### it is initial note ###
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable

  has_many :users_chats, dependent: :destroy
  has_many :chats, through: :users_chats
  has_many :owned_chats, class_name: 'Chat', foreign_key: :owner_id, dependent: :destroy
  has_many :messages
  has_many :blocked_users, class_name: 'BlockedUser', foreign_key: :user_id, dependent: :destroy

  enum role: [:user, :moderator]

  # validates :nickname, presence: true, length: { minimum: 2 }
  # validates :birthday, presence: true
  validate :birthday_in_past
  validates :max_chats, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  settings do
    mappings dynamic: false do
      indexes :nickname, type: :text
      indexes :email, type: :text
    end
  end

  def all_chats
    Chat.left_joins(:users)
        .where('users_chats.user_id = ? or chats.owner_id = ?', id, id)
        .distinct
  end

  def blocked_me_user_ids
    BlockedUser.where(blocked_user_id: id).map(&:user_id)
  end

  def blocked_user_ids
    blocked_users.map(&:blocked_user_id)
  end

  private

  def birthday_in_past
    if birthday.present? && birthday > Date.today
      errors.add(:birthday, "can't be in the future")
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_user, only: %i[show edit update]
  before_action :authenticate_moderator!, only: %i[manage apply_managing]

  def index
    @users = User.all.order(:id)

    if params.has_key? :search
      query_params = params.require(:search).permit(:q)
      query = query_params[:q]
      search_result = User.search(query)
      @founded_users_ids = search_result.map {|search| search.id.to_i}
    end
  end

  def edit; end

  def update
    birthday = user_params.delete(:birthday)
    if birthday.blank?
      @user.errors.add(:birthday, "Can't be blank")
      render :edit
      return
    end
    birthday = Date.parse(birthday)
    user_params[:birthday] = birthday

    if @user.update(user_params)
      redirect_to root_path, notice: 'Profile was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    current_user.destroy
    redirect_to root_path, notice: 'Account was successfully deleted.'
  end

  def manage
    @user = User.find(params[:id])
  end

  def apply_managing
    @user = User.find(params[:id])
    if @user.update(managed_user_params)
      redirect_to users_path, notice: 'New data for user is applied'
    else
      render :manage
    end
  end

  private

  def set_user
    @user = current_user
  end

  def user_params
    params.require(:user).permit(:nickname, :birthday, :no_invitation)
  end

  def managed_user_params
    result = params.require(:user).permit(:role, :max_chats).to_h
    result.each { |key, val| result[key] = val.to_i } # converting every str to int
  end

  def authenticate_moderator!
    unless current_user.moderator?
      redirect_to root_path, notice: 'You are not a moderator!'
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def user_row_class(highlighted = false)
    base = ''

    if highlighted
      base + ' list-group-item-warning'
    else
      base
    end
  end
end

app/views/users/_form.html.haml
= form_for(@user, url: { action: 'update'}, method: :post) do |form|
  - if @user.errors.any?
    #error_explanation
      .alert.alert-danger{:role => "alert"}
        = pluralize(@user.errors.count, "error")
        prohibited this profile from being saved.
  .form-group.row
    %label.col-sm-2.col-form-label{:for => "userNickname"} Nickname
    .col-sm-10
      = form.text_field :nickname, {class: "form-control", id: "userNickname" }
      - if @user.errors.messages[:nickname].present?
        .badge.badge-danger
          = @user.errors.messages[:nickname].join('; ')
  .form-group.row
    %label.col-sm-2.col-form-label{:for => "userBirthday"} Birthday
    .col-sm-10
      = form.date_field :birthday, {class: "form-control", id: "userBirthday" }
      - if @user.errors.messages[:birthday].present?
        .badge.badge-danger
          = @user.errors.messages[:birthday].join('; ')
  .form-group.form-check.row
    = form.check_box(:no_invitation, class: 'form-check-input')
    = form.label(:no_invitation, "Do not get invitation", class: 'form-check-label')
  .form-group.row
    .col-sm-10
      = form.submit class: "btn btn-primary"

app/views/users/_manage_form.html.haml
= form_for(@user, url: { action: 'apply_managing'}, method: :post) do |form|
  - if @user.errors.any?
    #error_explanation
      .alert.alert-danger{:role => "alert"}
        = pluralize(@user.errors.count, "error")
        prohibited this chat from being saved.
  %ul.list-group
    %li.list-group-item
      Nickname: #{@user.nickname}
    %li.list-group-item
      Email: #{@user.email}
  .form-group.row
    %label.col-sm-2.col-form-label{:for => "userRole"} Role
    .col-sm-10
      = form.select(:role, options_for_select(User.roles.to_a, current_user.role), {}, {class: "form-control", id: "userRole"})
  .form-group.row
    %label.col-sm-2.col-form-label{:for => "userMaxChats"} Quantity of allowed chats
    .col-sm-10
      = form.number_field :max_chats,                                                            |
        {class: "form-control", id: "userMaxChats", data: {toggle: "tooltip", placement: "top"}, |
         title:"Set 0 if you want to apply system setting for current user"                      |
        }                                                                                        |
      - if @user.errors.messages[:max_chats].present?
        .badge.badge-danger
          = @user.errors.messages[:max_chats].join('; ')
  .form-group.row
    .col-sm-10
      = form.submit class: "btn btn-primary"

app/views/users/edit.html.haml
%h1 My Profile
= render 'form'
%br/
%hr/
.row.h-100.justify-content-center.align-items-center
  = link_to 'Delete my account', delete_user_path(current_user), { method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" }
%hr/
%br/
= link_to 'Back', root_path

app/views/users/index.html.haml
= render 'general/flash', locals: {flash: flash}
%h1 List of Users
= form_for :search, url: users_path, method: :get do |form|
  = form.text_field :q
  = form.submit 'Search'
%br/
%table.table
  %thead.thead-light
    %tr
      %th{:scope => "col"} ID
      %th{:scope => "col"} Nickname
      %th{:scope => "col"} Email
      %th{:scope => "col"} Role
      - if current_user.role == "moderator"
        %th{:scope => "col"} Actions
  %tbody
    - @users.each do |user|
      - founded = @founded_users_ids.include?(user.id) if @founded_users_ids.present?
      %tr{:class => "#{user_row_class(founded)}"}
        %th= user.id
        %td= user.nickname
        %td= user.email
        %td= user.role
        - if current_user.role == "moderator"
          %td
            = link_to 'Manage', user_managing_path(user)

app/views/users/manage.html.haml
= render 'general/flash', locals: {flash: flash}
%h1 User managing
= render 'users/manage_form', user: @user
= link_to 'Back', root_path