config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  get '/users', to: 'users#index'
  get '/profile', to: 'users#edit'
  post '/profile', to: 'users#update'
  get '/users/:id/manage', to: 'users#manage', as: 'user_managing'
  post '/users/:id/apply_managing', to: 'users#apply_managing'
  delete '/users/:id/delete', to: 'users#destroy', as: 'delete_user'

  get '/black_list', to: 'blocked_users#index', as: 'black_list'
  get '/black_list/new', to: 'blocked_users#new', as: 'new_blocked_user'
  post '/black_list/add_user', to: 'blocked_users#add_user'
  delete '/blocked_user/:id/delete', to: 'blocked_users#destroy', as: 'delete_blocked_user'

  get 'chats/search', to: 'chats#search' # app interpreters 'search' as id. That is why it is on the first place
  resources :chats
  get '/chats/:id/users_list', to: 'chats#users_list', as: 'chat_users_list'
  post '/chats/:id/add_user', to: 'chats#add_user'
  post '/chats/:id/delete_user', to: 'chats#delete_user'
  get '/chats/:id/manage', to: 'chats#manage', as: 'chat_manging'
  post '/chats/:id/apply_managing', to: 'chats#apply_managing'
  post '/chats/:id/add_message', to: 'chats#add_message'

  get 'system_settings/edit', to: 'system_settings#edit', as: 'system_settings'
  post 'system_settings/update', to: 'system_settings#update'

  root to: "chats#index"
end

app/models/blocked_user.rb
class BlockedUser < ApplicationRecord
  belongs_to :user
  belongs_to :blocked_user, class_name: 'User'
end

app/controllers/blocked_users_controller.rb
class BlockedUsersController < ApplicationController
  before_action :authenticate_user!

  def index
    @blocked_users = current_user.blocked_users
  end

  def new
    @blocked_user = BlockedUser.new

    ids = current_user.blocked_users.pluck(:blocked_user_id).concat([current_user.id])
    @users = User.where.not(id: ids)
  end

  def add_user
    permitted_params = params.require(:blocked_user).permit(:blocked_user_id)
    @blocked_user = BlockedUser.new(permitted_params.merge(user_id: current_user.id))
    if @blocked_user.save
      redirect_to black_list_path, notice: 'User was added to black list.'
    end
  end

  def destroy
    set_blocked_user
    @blocked_user.destroy
    redirect_to black_list_path, notice: 'User is removed from black list.'
  end

  private

  def set_blocked_user
    if BlockedUser.exists?(params[:id])
      @blocked_user = BlockedUser.find(params[:id])
    else
      redirect_to black_list_path, alert: 'This user is absent in black list!'
    end
  end
end

app/helpers/blocked_users_helper.rb
module BlockedUsersHelper
end

app/views/blocked_users/_form.html.haml
= form_for(@blocked_user, url: { action: 'add_user'}, method: :post) do |form|
  .form-group
    %label{:for => "selectUsers"} Select users to Black List
    = form.collection_select(:blocked_user_id, @users, :id, :email, {prompt: 'Select user...'}, {class: "form-control", id: "selectUsers"})
    = form.submit 'Add User', class: "btn btn-primary"

app/views/blocked_users/index.html.haml
= render 'general/flash', locals: {flash: flash}
%h1 Black List
%table.table.table-striped
  %thead
    %tr
      %th{:scope => "col"} ID
      %th{:scope => "col"} Nickname
      %th{:scope => "col"} Email
      %th{:scope => "col"} Actions
  %tbody
    - @blocked_users.each do |blocked_user|
      - user = User.find(blocked_user.blocked_user_id)
      %tr
        %th= user.id
        %td= user.nickname
        %td= user.email
        %td
          = link_to 'Remove', delete_blocked_user_path(blocked_user), { method: :delete, data: { confirm: 'Are you sure?' } }
%br/
%a.btn.btn-primary.btn-lg.active{"aria-pressed" => "true", :href => new_blocked_user_path, :role => "button"} Add User

app/views/blocked_users/new.html.haml
%h1 Add user to Black List
= render 'form'
= link_to 'Back', black_list_path