config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  get '/users', to: 'users#index'
  get '/profile', to: 'users#edit'
  post '/profile', to: 'users#update'
  get '/users/:id/manage', to: 'users#manage', as: 'user_managing'
  post '/users/:id/apply_managing', to: 'users#apply_managing'
  delete '/users/:id/delete', to: 'users#destroy', as: 'delete_user'

  get '/black_list', to: 'blocked_users#index', as: 'black_list'
  get '/black_list/new', to: 'blocked_users#new', as: 'new_blocked_user'
  post '/black_list/add_user', to: 'blocked_users#add_user'
  delete '/blocked_user/:id/delete', to: 'blocked_users#destroy', as: 'delete_blocked_user'

  get 'chats/search', to: 'chats#search' # app interpreters 'search' as id. That is why it is on the first place
  resources :chats
  get '/chats/:id/users_list', to: 'chats#users_list', as: 'chat_users_list'
  post '/chats/:id/add_user', to: 'chats#add_user'
  post '/chats/:id/delete_user', to: 'chats#delete_user'
  get '/chats/:id/manage', to: 'chats#manage', as: 'chat_manging'
  post '/chats/:id/apply_managing', to: 'chats#apply_managing'
  post '/chats/:id/add_message', to: 'chats#add_message'

  get 'system_settings/edit', to: 'system_settings#edit', as: 'system_settings'
  post 'system_settings/update', to: 'system_settings#update'

  root to: "chats#index"
end

app/models/chat.rb
class Chat < ApplicationRecord
  has_many :users_chats, dependent: :destroy
  has_many :users, through: :users_chats
  belongs_to :owner, class_name: 'User'
  has_many :messages, dependent: :destroy

  accepts_nested_attributes_for :users_chats, allow_destroy: true, reject_if: :all_blank

  validates :name, presence: true
  validates :max_users, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
end

app/controllers/chats_controller.rb
class ChatsController < ApplicationController
  before_action :set_chat, only: %i[show edit update destroy add_user users_list delete_user manage apply_managing]
  before_action :authenticate_user!
  before_action :authenticate_owner_or_moderator!, only: %i[destroy users_list add_user delete_user]
  before_action :authenticate_moderator!, only: %i[manage apply_managing]

  # GET /chats
  def index
    @allowed_to_create = allowed_to_creat_chat?
    @chats = policy_scope(Chat).order(:id)
  end

  # GET /chats/1
  def show
    @allowed_to_add_user = allowed_to_add_user?

    @users = @chat.users
    @owner = @chat.owner

    if params.has_key? :search
      query_params = params.require(:search).permit(:q)
      query = query_params[:q]
      search_result = Message.search_in_chat(query, @chat.id)
      @founded_messages_ids = search_result.map {|search| search.id.to_i}
    end

    if @owner.id == current_user.id || @users.ids.include?(current_user.id) || current_user.moderator?
      @messages = @chat.messages.order(id: :desc).limit(100).reverse
      unless @messages.present?
        flash[:notice] = "No one message in this chat. Type something... You will be first!"
      end
    else
      redirect_to chats_path, alert: 'You do not have access to this chat!'
    end
  end

  # GET /chats/new
  def new
    @chat = Chat.new
    @chat.users_chats.build
  end

  # GET /chats/1/edit
  def edit
    authorize @chat
  end

  # POST /chats
  def create
    allowed_to_create = allowed_to_creat_chat?

    @chat = Chat.new(chat_params.merge(owner_id: current_user.id))

    if allowed_to_create && @chat.save
      redirect_to @chat, notice: 'Chat was successfully created.'
    else
      if allowed_to_create
        errors = @chat.errors.full_messages.join(', ')
        @chat = Chat.new
        @chat.users_chats.clear
        @chat.users_chats.build
        render :new, notice: errors
      else
        redirect_to :chats, alert: @msg_not_allowed_to_creat_chat
      end
    end
  end

  # PATCH/PUT /chats/1
  def update
    authorize @chat
    if @chat.update(chat_params)
      redirect_to @chat, notice: 'Chat was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /chats/1
  def destroy
    authorize @chat
    @chat.destroy
    redirect_to chats_url, notice: 'Chat was successfully destroyed.'
  end

  def users_list
    @users = User.where.not(id: @chat.user_ids.concat([@chat.owner_id]))
                 .where.not(id: current_user.blocked_user_ids)
                 .where.not(id: current_user.blocked_me_user_ids)
                 .where(no_invitation: false)
  end

  def add_user
    @allowed_to_add_user = allowed_to_add_user?

    user_id = params[:user_id]
    if user_id.nil?
      message = 'You can\'t add empty user'
    elsif @chat.user_ids.include?(user_id)
      message = 'User already is a member of the chat'
    elsif !@allowed_to_add_user
      message = @msg_not_allowed_to_add_user
    else
      user = User.find(user_id)
      if user.no_invitation
        message = 'User cannot be added'
      else
        @chat.users << user
        message = 'User successfully added'
      end
    end

    redirect_to(@chat, notice: message)
  end

  def delete_user
    @user_id = params[:user_id]

    if @user_id.blank?
      message = 'You can\'t delete empty user'
    elsif @chat.user_ids.exclude?(@user_id.to_i)
      message = 'This user isn\'t a member of the chat'
    else
      @chat.users.delete(@user_id.to_i)
      message = 'You successfully delete user from the chat'
    end

    respond_to do |format|
      format.html { redirect_to @chat, notice: message }
      format.js
    end
  end

  def manage; end

  def apply_managing
    if @chat.update(managed_chat_params)
      redirect_to chats_path, notice: 'New data for chat is applied.'
    else
      render :manage
    end
  end

  def add_message
    chat_id = params[:id]
    message_params = new_message_params.merge(user_id: current_user.id, chat_id: chat_id)
    if message_params[:message].present?
      @message = Message.create(message_params)
    else
      @message = Message.new(message_params)
      @alert = "You can't send empty message"
    end

    MessageBroadcastJob.perform_later(@message, current_user.id)

    # respond_to do |format|
    #   format.html { redirect_to @chat, alert: @alert }
    #   format.js
    # end
  end

  def search
    query_params = params.require(:search).permit(:q)
    query = query_params[:q]
    @search_result = Message.search(query)

    unless current_user.moderator?
      user_chat_ids = current_user.all_chats.pluck(:id)
      @search_result = @search_result.select do |search|
        user_chat_ids.include?(search.chat_id)
      end
    end

    render :search_result
  rescue StandardError
    redirect_to :chats, alert: 'Sorry, search index is not ready. Try it a little bit later.'
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_chat
    if Chat.exists?(params[:id])
      @chat = Chat.find(params[:id])
    else
      redirect_to root_path, alert: 'This chat does not exist or wrong URL!'
    end
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def chat_params
    params.require(:chat).permit(:name, users_chats_attributes: [:user_id, :id, :_destroy])
  end

  def new_message_params
    params.require(:message).permit(:message).to_h
  end

  def authenticate_owner_or_moderator!
    unless current_user.moderator? || current_user.id == @chat.owner_id
      redirect_to @chat, alert: 'You are not an owner!'
    end
  end

  def managed_chat_params
    result = params.require(:chat).permit(:max_users).to_h
    result.each { |key, val| result[key] = val.to_i } # converting every str to int
  end

  def authenticate_moderator!
    unless current_user.moderator?
      redirect_to root_path, alert: 'You are not a moderator!'
    end
  end

  def allowed_to_creat_chat?
    if current_user.moderator?
      allowed_to_create = true
    else
      quantity_of_allowed_chats = current_user.max_chats
      if quantity_of_allowed_chats == 0 # max chats value is not defined
        quantity_of_allowed_chats = SystemSetting.first.chats_count_for_user
      end
      user_chats_count = Chat.where(owner_id: current_user.id).count
      allowed_to_create = user_chats_count < quantity_of_allowed_chats
      @msg_not_allowed_to_creat_chat = "You are not allowed to create more than #{quantity_of_allowed_chats} chats!"
    end

    allowed_to_create
  end

  def allowed_to_add_user?
    if current_user.moderator?
      allowed_to_add = true
    else
      quantity_of_allowed_users = @chat.max_users
      if quantity_of_allowed_users == 0 # max users value is not defined
        quantity_of_allowed_users = SystemSetting.first.users_count_for_chat
      end
      users_in_chat = @chat.users.count + 1 # with owner
      allowed_to_add = users_in_chat < quantity_of_allowed_users
      @msg_not_allowed_to_add_user = "You are not allowed to add more than #{quantity_of_allowed_users} users!"
    end

    allowed_to_add
  end
end

app/helpers/chats_helper.rb
module ChatsHelper
  def message_class(highlighted = false)
    base = "list-group-item d-flex justify-content-between align-items-center"

    if highlighted
      base + " list-group-item-warning"
    else
      base
    end
  end
end

app/views/chats/_form.html.haml
= form_with(model: chat, local: true) do |form|
  - if chat.errors.any?
    #error_explanation
      .alert.alert-danger{:role => "alert"}
        = pluralize(chat.errors.count, "error")
        prohibited this chat from being saved.
  .form-group.row
    %label.col-sm-2.col-form-label{:for => "chatName"} Name
    .col-sm-10
      = form.text_field :name, {class: "form-control", id: "chatName" }
      - if chat.errors.messages[:name].present?
        .badge.badge-danger
          = chat.errors.messages[:name].join('; ')
  = form.fields_for :users_chats do |users_chats_form|
    = render 'users_chat_fields', f: users_chats_form
    .links
      = link_to_add_association 'add', form, :users_chats
  .form-group.row
    .col-sm-10
      = form.submit class: "btn btn-primary"

app/views/chats/_manage_form.html.haml
= form_for(@chat, url: { action: 'apply_managing'}, method: :post) do |form|
  - if @chat.errors.any?
    #error_explanation
      .alert.alert-danger{:role => "alert"}
        = pluralize(@chat.errors.count, "error")
        prohibited this chat from being saved.
  %ul.list-group
    %li.list-group-item
      Name: #{@chat.name}
    %li.list-group-item
      Owner: #{@chat.owner.email}
  .form-group.row
    %label.col-sm-2.col-form-label{:for => "userMaxUsers"} Quantity of allowed users
    .col-sm-10
      = form.number_field :max_users,                                                            |
        {class: "form-control", id: "userMaxUsers", data: {toggle: "tooltip", placement: "top"}, |
         title:"Set 0 if you want to apply system setting for current chat"                      |
        }                                                                                        |
      - if @chat.errors.messages[:max_users].present?
        .badge.badge-danger
          = @chat.errors.messages[:max_users].join('; ')
  .form-group.row
    .col-sm-10
      = form.submit class: "btn btn-primary"

app/views/chats/_message.html.erb
<li class="list-group-item d-flex justify-content-between align-items-center">
  <%= message.message %> <%= ApplicationController.helpers.message_owner(message.user) %>
</li>

app/views/chats/_users_chat_fields.html.haml
.nested-fields
  = f.collection_select(:user_id, User.all, :id, :email)
  = link_to_remove_association "remove", f

app/views/chats/add_message.js.erb
var msg = '<%= j @alert || '' %>'
if ($.trim(msg).length === 0) {
  $("#chat_messages")
    .append("<li class=\"list-group-item d-flex justify-content-between align-items-center\"><%= j @message.message %> <%= j message_owner(@message.user) %></li>");
} else {
  alert("You can't send empty message");
}
$("#message_message").val('');

app/views/chats/delete_user.js.haml
$("#user_in_chat#{@user_id}").remove();

app/views/chats/edit.html.haml
%h1 Editing Chat
= render 'form', chat: @chat
= link_to 'Show', @chat
|
= link_to 'Back', chats_path

app/views/chats/index.html.haml
= render 'general/flash', locals: {flash: flash}
%h1 Chats
= form_for :search, url: chats_search_path, method: :get do |form|
  = form.text_field :q
  = form.submit 'Search'
%table.table.table-striped
  %thead
    %tr
      %th{:scope => "col"} ID
      %th{:scope => "col"} Name
      %th{:scope => "col"} Owner
      %th{:scope => "col"} Actions
  %tbody
    - @chats.each do |chat|
      %tr
        %th= chat.id
        %td= chat.name
        %td
          - if chat.owner_id == current_user.id
            me
          - else
            = User.find(chat.owner_id).email
        %td
          = link_to 'Show', chat
          - if current_user.id == chat.owner_id || current_user.moderator?
            | #{link_to 'Edit', edit_chat_path(chat)}
            | #{link_to 'Destroy', chat, { method: :delete, data: { confirm: 'Are you sure?' } }}
          - if current_user.moderator?
            | #{link_to 'Manage', chat_manging_path(chat)}
%br/
- btn_name = 'New Chat'
- if @allowed_to_create
  %a.btn.btn-primary.btn-lg.active{"aria-pressed" => "true", :href => new_chat_path, :role => "button"}= btn_name
- else
  %button.btn.btn-lg.btn-primary{"data-placement" => "bottom", "data-toggle" => "tooltip", :disabled => "disabled", :title => "#{@msg_not_allowed_to_creat_chat}", :type => "button"}= btn_name
  .alert.alert-light{:role => "alert"}
    = @msg_not_allowed_to_creat_chat

app/views/chats/manage.html.haml
= render 'general/flash', locals: {flash: flash}
%h1 Chat managing
= render 'chats/manage_form', chat: @chat
= link_to 'Back', root_path

app/views/chats/new.html.haml
= render 'general/flash', locals: {flash: flash}
%h1 New Chat
= render 'form', chat: @chat
= link_to 'Back', chats_path

app/views/chats/search_result.html.haml
= render 'general/flash', locals: {flash: flash}
%h1 Search result for all chats
%table.table.table-striped
  %thead
    %tr
      %th.text-center{:scope => "col"} Message
  %tbody
    - @search_result.each do |search|
      %tr
        %th= link_to search.message.truncate(30), chat_path(search.chat_id)
%br/
= link_to 'Back', chats_path, class: 'btn btn-primary'

app/views/chats/show.html.erb
<%= render 'general/flash', locals: {flash: flash} %>


<%= form_for :search, url: chat_path(@chat), method: :get do |form| %>
  <%= form.text_field :q %>
  <%= form.submit 'Search' %>
<% end %>


<div class="container">
  <div class="row">
    <p>
      <strong>Name:</strong>
      <%= @chat.name %>
    </p>
  </div>
  <div class="row">



    <div class="col-8">
      <div class="messages" style="height: 600px;">

        <h3>Messages:</h3>
        <ul class="list-group" id="chat_messages" data-chat-id="<%= @chat.id %>">
          <% @messages.each do |msg| %>
            <% founded = @founded_messages_ids.include?(msg.id) if @founded_messages_ids.present? %>
            <li class="<%= message_class(founded) %>">
              <%= msg.message %>
              <%= message_owner(msg.user) %>
            </li>
          <% end %>
        </ul>
      </div>
      <%= form_for :message, url: { action: :add_message }, method: :post, remote: true do |f| %>
        <%= f.text_area :message, class: "form-control", placeholder: "Type a message" %>
        <%= f.submit 'Send message', class: "btn btn-primary" %>
      <% end %>
    </div>






    <div class="col-4">
      Users:
      <% btn_name = 'Add User' %>
      <% if current_user.id == @owner.id %>
        <% if @allowed_to_add_user %>
          <%= link_to btn_name, chat_users_list_path(@chat), class: "btn btn-primary" %>
        <% else %>
          <button type="button" class="btn btn-lg btn-primary" disabled data-toggle="tooltip" data-placement="bottom" title="<%= @msg_not_allowed_to_add_user %>"><%= btn_name %></button>
          <div class="alert alert-light" role="alert">
            <%= @msg_not_allowed_to_add_user %>
          </div>
        <% end %>
      <% end %>
      <ul class="list-group">
        <li href="#" class="list-group-item list-group-item-action active"><%= @owner.email %> (Owner)</li>
        <% @users.each do |user| %>
          <li href="#" class="list-group-item list-group-item-action" id="user_in_chat<%= user.id %>">
            <%= user.email %>
            <% if current_user.id == @owner.id %>
              <%= form_for @chat, url: { action: 'delete_user'}, method: :post, remote: true do |form| %>
                <div class="form-group">
                  <%= hidden_field_tag 'user_id', user.id %>
                  <%= form.submit 'Delete', class: "btn btn-danger" %>
                </div>
              <% end %>
            <% end %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

<% if policy(@chat).update? %>
  <%= link_to 'Edit', edit_chat_path(@chat) %> |
  <%= link_to 'Back', chats_path %>
<% end %>

app/views/chats/users_list.html.haml
= form_for @chat, url: { action: 'add_user'}, method: :post  do |form|
  .form-group
    %label{:for => "selectUsers"} Select users for chat
    %select#selectUsers.form-control{:name => "user_id"}
      - @users.each do |user|
        %option{:value => "#{user.id}"}= user.email
    = form.submit 'Add Users', class: "btn btn-primary"