config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  get '/users', to: 'users#index'
  get '/profile', to: 'users#edit'
  post '/profile', to: 'users#update'
  get '/users/:id/manage', to: 'users#manage', as: 'user_managing'
  post '/users/:id/apply_managing', to: 'users#apply_managing'
  delete '/users/:id/delete', to: 'users#destroy', as: 'delete_user'

  get '/black_list', to: 'blocked_users#index', as: 'black_list'
  get '/black_list/new', to: 'blocked_users#new', as: 'new_blocked_user'
  post '/black_list/add_user', to: 'blocked_users#add_user'
  delete '/blocked_user/:id/delete', to: 'blocked_users#destroy', as: 'delete_blocked_user'

  get 'chats/search', to: 'chats#search' # app interpreters 'search' as id. That is why it is on the first place
  resources :chats
  get '/chats/:id/users_list', to: 'chats#users_list', as: 'chat_users_list'
  post '/chats/:id/add_user', to: 'chats#add_user'
  post '/chats/:id/delete_user', to: 'chats#delete_user'
  get '/chats/:id/manage', to: 'chats#manage', as: 'chat_manging'
  post '/chats/:id/apply_managing', to: 'chats#apply_managing'
  post '/chats/:id/add_message', to: 'chats#add_message'

  get 'system_settings/edit', to: 'system_settings#edit', as: 'system_settings'
  post 'system_settings/update', to: 'system_settings#update'

  root to: "chats#index"
end

app/views/layouts/_navbar.html.haml
%nav.navbar.navbar-expand-lg.navbar-light.bg-light
  %a.navbar-brand{:href => "#"} MyChat App
  %button.navbar-toggler{"aria-controls" => "navbarNavAltMarkup", "aria-expanded" => "false", "aria-label" => "Toggle navigation", "data-target" => "#navbarNavAltMarkup", "data-toggle" => "collapse", :type => "button"}
    %span.navbar-toggler-icon
  #navbarNavAltMarkup.collapse.navbar-collapse
    .navbar-nav
      - if user_signed_in?
        %a.nav-item.nav-link.active{:href => root_path}
          Home
          %span.sr-only (current)
        %a.nav-item.nav-link{:href => users_path} Users
        %a.nav-item.nav-link{:href => chats_path} Chats
        %a.nav-item.nav-link{:href => black_list_path} Black list
        - if current_user.moderator?
          %a.nav-item.nav-link{:href => system_settings_path} Settings
        = link_to('Profile', profile_path, class: "nav-item nav-link")
        = link_to("Logout #{user_presentation_text(current_user)}", destroy_user_session_path, method: :delete, class: "nav-item nav-link #{user_presentation_class(current_user)}")
      - else
        = link_to('Login', new_user_session_path, class: "nav-item nav-link")

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title MySuperChat
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    .container
      = render "layouts/navbar"
      = yield